### PR TITLE
Fix: episode file url

### LINKED ISSUE #573: Player does not record statistics
I have been doing several tests, and apparently, the reproductions are not recorded in any of the audio players of any of my pages (I have 4 podcasts in different websites) I tried with the default player and with the htlm, also with unknown connections, with different browsers and plays are not logged.

[Screencast](https://vimeo.com/491581063/cfc7b71d23)

In the video, I show you the statistics before the [reproduction of an episode] (https://renzodangelo.me/forma-tu-propia-manada/) in the Player in Firefox, and as you can see, it does not register the reproductions. I have done this same test from other browsers, as incognito with session, clearing cache, and in no case does it record the statistics.

The same happens in the 4 sites where I have installed the plugin and with all the audios. The sites have in common the latest version of WP 5.6, Genesis 3.3.3. (With the [Support plugin of SSP](https://wordpress.org/plugins/seriously-simple-podcasting-genesis-support/) I have also turned this off and the problem continues)

This flaw is present exactly from update 2.5. It's a terrible flaw, especially since on my sites, most of the views come from their web pages.

### PR DESCRIPTION
**Pull request by barthc**
Closes #573, and also fixes the file URL for all other instances of the media player.

The reason why version 2.4.2 works for inline media player is probably because of this  line https://github.com/CastosHQ/Seriously-Simple-Podcasting/blob/90d707577642790ae754fd3db865bba884b024ec/php/classes/controllers/class-frontend-controller.php#L438

### CODE REVIEW

**Comment by jonathanbossenger** [comment]
@barthc is there any way you can update your forked version of the repository? The pull request contains commits all the way back to Nov 23, which makes it impossible to review just the work to be merged.

It can be done either via the GitHub UI - https://adrientorris.github.io/github/how-to-update-a-forked-repository-from-the-ui-on-github

Or via the command line - https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/syncing-a-fork

**Comment by barthc** [comment]
@jonathanbossenger  My fork is up to date. The issue here is that the PR is opened on the `develop` branch as suggested in the [contribution guide](https://github.com/CastosHQ/Seriously-Simple-Podcasting/blob/master/CONTRIBUTING.md). I just changed the base branch to `master`

**Comment by jonathanbossenger** [comment]
@barthc Ah yes, my apologies, you are correct.

I've rebased `develop` and updated this back to be merged into `develop`, thanks.

**Comment by jonathanbossenger** [comment]
@barthc thanks for the PR, looks good so far.

I do have one change request. While changing the meta audio_file field in the REST API is a solid solution, for the Castos importer, the audio_file field must remind the raw audio file URL.

In order to enable the player URL for the Castos Player block, instead of rewriting the audio_file field in the episodes route, I would prefer it if you added a new `player_link` REST API field in the same way that we the `download_link` field here: https://github.com/CastosHQ/Seriously-Simple-Podcasting/blob/77e714bb77061bafa1b0873d82c2d46fdf36d613/php/classes/rest/class-rest-api-controller.php#L75

That way it leaves the default data is as, meaning it has no effect on external services relying on the raw audio_file URL, but also allows us to use the correct URL in the player block.

Let me know if you have any questions about this.

File: php/classes/controllers/class-admin-controller.php [hunk 1]
```diff
@@ -67,6 +67,8 @@ public function bootstrap() {
 
 		$this->feed_controller = new Feed_Controller( $this->file, $this->version );
 
+		$this->episode_controller = new Episode_Controller( $this->file, $this->version );
```
Comment (jonathanbossenger) [inline php/classes/controllers/class-admin-controller.php]: Is this episode_controller property on the admin_controller still needed?

**Review by jonathanbossenger — CHANGES_REQUESTED** [review]
Looks good so far, just one small change request. Thanks. Will test this out in the week.

File: php/classes/controllers/class-admin-controller.php (hunk 1 above)
Comment (barthc) [reply php/classes/controllers/class-admin-controller.php]: Nope, it's not needed, I have removed it. Nice catch :+1:
